# Dockerfile
FROM node:20.9.0-alpine3.17

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY .env ./.env
COPY src src
COPY tsconfig.json ./tsconfig.json

RUN npm run build

CMD npm start

# docker build -t tgc-backend-prod -f dockerfile.production .